<header id="begin">
  <div>
    <h1>Projeto Learning</h1>

    <details open>
      <summary>Ir para...</summary>

      <nav>
        <div>
          <ul>
            <li><a href="#section01">Aula 01</a></li>
            <li><a href="#section02">Aula 02</a></li>
            <li><a href="#section03">Aula 03</a></li>
            <li><a href="#section04">Aula 04</a></li>
            <li><a href="#section05">Aula 05</a></li>
            <li><a href="#section06">Aula 06</a></li>
            <li><a href="#section07">Aula 10</a></li>
            <li><a href="#section08">Aula 11</a></li>
            <li><a href="#section09">Aula 12</a></li>
          </ul>
        </div>
      </nav>
    </details>
  </div>
</header>